### ISSUE TITLE
Assignment 2

### ISSUE THREAD

**Issue by nickwp54** [nickwp54/StockMarketGame#1]
This will be the issue tracking for assignment 2.

**Comment by mattvr** [comment]
Let's meet up and work on this.

**Comment by nickwp54** [comment]
Ok when, how about now in the CS Lounge.

**Comment by mattvr** [comment]
Sounds good. Meet you in the back room with the whiteboards.

**Comment by nickwp54** [comment]
Adding more use cases to get to 16.

**Comment by mattvr** [comment]
Submitted.
