### ISSUE TITLE
System Sequence Diagrams

### ISSUE THREAD

**Issue by nickwp54** [nickwp54/StockMarketGame#2]
Draw one system sequence diagram for each one of the fully-dressed use cases that were requestedin Assignment 1. You should submit a total of 16 system sequence diagrams.The terminology used in this diagram should be consistent with the one used in your requirements analysis.

**Comment by nickwp54** [comment]
Taking the use cases from assignment 1 and creating system sequence diagrams

**Comment by mattvr** [comment]
We've finished these.
