### ISSUE TITLE
Database entity-relationship diagram

### ISSUE THREAD

**Issue by mattvr** [nickwp54/StockMarketGame#6]
Complete for Assignment 3.

**Comment by nickwp54** [comment]
Beginning work for this by reviewing the work done so far on: Class Diagram and Database Tables. 

The database tables could be done with the tool vertabelo : https://www.vertabelo.com/

**Comment by nickwp54** [comment]
Looking at the current class diagram and taking the terms to make a version with all the needed terms just not ordered. 

Uploaded it as an original version.

**Comment by nickwp54** [comment]
Didn't like working in word so I switched to draw.io

**Comment by nickwp54** [comment]
Did a first final copy with draw.io. Going to sleep
